image:
- Visual Studio 2022
- Ubuntu
init:
  - git config --global core.autocrlf input
build:
  verbosity: detailed
before_build:
  - dotnet --list-sdks
  - dotnet --version
build_script:
  - dotnet run --project ./tests/Snowflaqe.Tests.fsproj
  - dotnet restore ./build/Snowflaqe.Build.fsproj
  - dotnet run --project ./build/Snowflaqe.Build.fsproj -- integration
test: off
