init:
  - git config --global core.autocrlf input

build:
  verbosity: detailed

install:
  # install latest dotnet 5
  - cmd: choco install dotnet

os: Visual Studio 2019

build_script:
  - cmd: dotnet run --project ./tests/Snowflaqe.Tests.fsproj
  - cmd: dotnet restore --project ./build/Snowflaqe.Build.fsproj
  - cmd: dotnet run --project ./build/Snowflaqe.Build.fsproj -- integration

test: off
